services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - wwn_mgr_network
    depends_on:
      - wwn_webapi
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./dist/:/usr/share/nginx/html/wwnmgr/:ro
  wwn_webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
      args:
        IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    image: wwn_webapi:0.0.1
    networks:
      - wwn_mgr_network
    # ports:
    #   - "8888:8888"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    environment:
      MONGO_URI: mongodb://mongodb_wwnmgr:27017/
  frontend-artifacts:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile   # or reuse the same commands as frontend-builder
      # args:
      #   IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    volumes:
      - ./dist:/output
    entrypoint: sh -c
    command: ["cp -r /app/dist/* /output/"]
  mongodb:
    image: mongo:7
    container_name: mongodb_wwnmgr
    restart: always
    networks:
      - wwn_mgr_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
networks:
  wwn_mgr_network: {}
volumes:
  mongo-data: