services:
  wwn_webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    image: wwn_webapi:0.0.1
    ports:
      - "8889:8888"
    networks:
      - xapoc_agent_poc_network
    restart: always
    volumes:
      - ./logs:/app/logs
    environment:
      MONGO_URI: mongodb://mongodb:27017/
  frontend-artifacts:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./dist:/output
    entrypoint: sh -c
    command: ["cp -r /app/dist/* /output/"]
networks:
  xapoc_agent_poc_network:

    external: true
