name: Deploy via SSH

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            mkdir -p /wwnmgr
            cd /wwnmgr
            git pull
            sudo docker compose build
            echo "Build done"
            sudo systemctl restart wwnmgr
            echo "Systemctl restart done"
